### ISSUE TITLE
Cannot connect to a different port.

### ISSUE THREAD

**Issue by ishanrakitha** [ameir/mysqlbackup#5]
MySQL Server is running on 3340, script fails to connect.

DBHOST[0]="127.0.0.1:3340" 
Error - Got error: 2005: Unknown MySQL server host '127.0.0.1:3340' (2) when trying to connect.

**Comment by ameir** [comment]
Thanks for your feedback!  You should be all set now with commit 1f6de0a06dfdd4c512141211f0ce2afe9659c10e .  Let me know if you run into any issues!
